// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package destination

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigAzureClientId      = "azure.clientId"
	ConfigAzureClientSecret  = "azure.clientSecret"
	ConfigAzureTenantId      = "azure.tenantId"
	ConfigBatchSamePartition = "batchSamePartition"
	ConfigEventHubName       = "eventHubName"
	ConfigEventHubNamespace  = "eventHubNamespace"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigAzureClientId: {
			Default:     "",
			Description: "AzureClientID is the azure client ID",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAzureClientSecret: {
			Default:     "",
			Description: "AzureClientSecret is the azure client secret",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAzureTenantId: {
			Default:     "",
			Description: "AzureTenantID is the azure tenant ID",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigBatchSamePartition: {
			Default:     "false",
			Description: "BatchSamePartition is a boolean that controls whether to write batches of records to the same partition\nor to divide them among available partitions according to the azure event hubs producer client",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		ConfigEventHubName: {
			Default:     "",
			Description: "EventHubName is your event hub name- analogous to a kafka topic",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigEventHubNamespace: {
			Default:     "",
			Description: "EventHubNameSpace is the FQNS of your event hubs resource",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
