// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package source

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigAzureClientId     = "azure.clientId"
	ConfigAzureClientSecret = "azure.clientSecret"
	ConfigAzureTenantId     = "azure.tenantId"
	ConfigEventHubName      = "eventHubName"
	ConfigEventHubNamespace = "eventHubNamespace"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigAzureClientId: {
			Default:     "",
			Description: "AzureClientID is the azure client ID",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAzureClientSecret: {
			Default:     "",
			Description: "AzureClientSecret is the azure client secret",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAzureTenantId: {
			Default:     "",
			Description: "AzureTenantID is the azure tenant ID",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigEventHubName: {
			Default:     "",
			Description: "EventHubName is your event hub name- analogous to a kafka topic",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigEventHubNamespace: {
			Default:     "",
			Description: "EventHubNameSpace is the FQNS of your event hubs resource",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
